---

- hosts: all
  become: true
  tasks:
  
  - name: install httpd and php packages in CentOS
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
